save :- open('savedfile.dat', write, Stream),
                  set_output(Stream),
                  listing(alreadystart),
                  listing(attack),
                  listing(class),
                  listing(defense),
                  listing(exp),
                  listing(gold),
                  listing(health),
                  listing(ketemuMusuh),
                  listing(level),
                  listing(positionPlayer),
                  listing(specialattack),
                  listing(speed),
                  close(Stream).